### ISSUE TITLE
        self.experiment_config.update(EXPERIMENT_CONFIG) in experiment 2 doesn't really work!

### ISSUE THREAD

**Issue by hekmak** [layssi/Carla_Ray_Rlib#1]

**Comment by layssi** [comment]
It does. Please add the following code and re-check.

def __init__(self):
        super().__init__()
        print("Config Before:", self.experiment_config["OBSERVATION_CONFIG"]["CAMERA_OBSERVATION"])
        self.experiment_config.update(EXPERIMENT_CONFIG)
        print("Config After:", self.experiment_config["OBSERVATION_CONFIG"]["CAMERA_OBSERVATION"])

**Comment by layssi** [comment]
Fixed
